// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBJeoqwThk2mUaqWTOjaGbOmQTOeksT1go',
    appId: '1:47330829614:android:37421093af07e2692146bf',
    messagingSenderId: '47330829614',
    projectId: 'flutter-phone-auth-184e3',
    storageBucket: 'flutter-phone-auth-184e3.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCHGdJ_cQLBwPJDjqp8aOXeffLDLeqcMWg',
    appId: '1:47330829614:ios:5999b1c4bff2faae2146bf',
    messagingSenderId: '47330829614',
    projectId: 'flutter-phone-auth-184e3',
    storageBucket: 'flutter-phone-auth-184e3.appspot.com',
    androidClientId: '47330829614-0ct3ikipgoinmu1lg6bv5h99ndur2gi6.apps.googleusercontent.com',
    iosClientId: '47330829614-dlcjr6iarrrv9fnh1v9cus8p95ubqt6h.apps.googleusercontent.com',
    iosBundleId: 'com.example.phoneAuthFirbase',
  );
}
